import { Category } from '@/types';

export interface ServiceInfo {
  name: string;
  domain: string;
  brandColor: string;
  category: Category;
  cancelUrl?: string;
  aliases?: string[];
}

export const SERVICE_REGISTRY: ServiceInfo[] = [
  // ─── STREAMING ─────────────────────────────────────────────
  {
    name: 'Netflix',
    domain: 'netflix.com',
    brandColor: '#E50914',
    category: Category.STREAMING,
    cancelUrl: 'https://www.netflix.com/cancelplan',
    aliases: ['nflx'],
  },
  {
    name: 'Disney+',
    domain: 'disneyplus.com',
    brandColor: '#113CCF',
    category: Category.STREAMING,
    cancelUrl: 'https://www.disneyplus.com/account/subscription',
    aliases: ['disney plus', 'disney'],
  },
  {
    name: 'HBO Max',
    domain: 'max.com',
    brandColor: '#5822B4',
    category: Category.STREAMING,
    cancelUrl: 'https://www.max.com/account/subscription',
    aliases: ['hbo', 'max', 'hbo max'],
  },
  {
    name: 'Amazon Prime Video',
    domain: 'primevideo.com',
    brandColor: '#00A8E1',
    category: Category.STREAMING,
    cancelUrl: 'https://www.amazon.com/gp/primecentral',
    aliases: ['prime video', 'amazon prime', 'prime'],
  },
  {
    name: 'Hulu',
    domain: 'hulu.com',
    brandColor: '#1CE783',
    category: Category.STREAMING,
    cancelUrl: 'https://secure.hulu.com/account',
    aliases: [],
  },
  {
    name: 'Paramount+',
    domain: 'paramountplus.com',
    brandColor: '#0064FF',
    category: Category.STREAMING,
    cancelUrl: 'https://www.paramountplus.com/account/',
    aliases: ['paramount plus', 'paramount'],
  },
  {
    name: 'Crunchyroll',
    domain: 'crunchyroll.com',
    brandColor: '#F47521',
    category: Category.STREAMING,
    aliases: ['crunchy'],
  },
  {
    name: 'Apple TV+',
    domain: 'tv.apple.com',
    brandColor: '#000000',
    category: Category.STREAMING,
    cancelUrl: 'https://support.apple.com/en-us/HT202039',
    aliases: ['apple tv', 'apple tv plus', 'appletv'],
  },
  {
    name: 'DAZN',
    domain: 'dazn.com',
    brandColor: '#F8F8F5',
    category: Category.STREAMING,
    cancelUrl: 'https://www.dazn.com/account',
    aliases: [],
  },
  {
    name: 'YouTube Premium',
    domain: 'youtube.com',
    brandColor: '#FF0000',
    category: Category.STREAMING,
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    aliases: ['youtube', 'yt premium', 'yt'],
  },

  // ─── MÚSICA ────────────────────────────────────────────────
  {
    name: 'Spotify',
    domain: 'spotify.com',
    brandColor: '#1DB954',
    category: Category.MUSIC,
    cancelUrl: 'https://www.spotify.com/account/subscription/',
    aliases: [],
  },
  {
    name: 'Apple Music',
    domain: 'music.apple.com',
    brandColor: '#FA2D48',
    category: Category.MUSIC,
    cancelUrl: 'https://support.apple.com/en-us/HT202039',
    aliases: ['apple music'],
  },
  {
    name: 'YouTube Music',
    domain: 'music.youtube.com',
    brandColor: '#FF0000',
    category: Category.MUSIC,
    cancelUrl: 'https://www.youtube.com/paid_memberships',
    aliases: ['yt music'],
  },
  {
    name: 'Tidal',
    domain: 'tidal.com',
    brandColor: '#000000',
    category: Category.MUSIC,
    cancelUrl: 'https://account.tidal.com/subscription',
    aliases: [],
  },
  {
    name: 'Deezer',
    domain: 'deezer.com',
    brandColor: '#A238FF',
    category: Category.MUSIC,
    cancelUrl: 'https://www.deezer.com/account/subscription',
    aliases: [],
  },
  {
    name: 'SoundCloud Go',
    domain: 'soundcloud.com',
    brandColor: '#FF5500',
    category: Category.MUSIC,
    cancelUrl: 'https://soundcloud.com/settings/account',
    aliases: ['soundcloud', 'soundcloud go+'],
  },
  {
    name: 'Amazon Music',
    domain: 'music.amazon.com',
    brandColor: '#25D1DA',
    category: Category.MUSIC,
    aliases: ['amazon music unlimited'],
  },

  // ─── GAMING ────────────────────────────────────────────────
  {
    name: 'Xbox Game Pass',
    domain: 'xbox.com',
    brandColor: '#107C10',
    category: Category.GAMING,
    cancelUrl: 'https://account.microsoft.com/services/',
    aliases: ['game pass', 'xbox', 'gamepass'],
  },
  {
    name: 'PlayStation Plus',
    domain: 'playstation.com',
    brandColor: '#003791',
    category: Category.GAMING,
    cancelUrl: 'https://store.playstation.com/subscriptions',
    aliases: ['ps plus', 'psn', 'ps+', 'playstation'],
  },
  {
    name: 'Nintendo Switch Online',
    domain: 'nintendo.com',
    brandColor: '#E60012',
    category: Category.GAMING,
    cancelUrl: 'https://accounts.nintendo.com/shop/subscription',
    aliases: ['nintendo online', 'nso', 'nintendo'],
  },
  {
    name: 'EA Play',
    domain: 'ea.com',
    brandColor: '#000000',
    category: Category.GAMING,
    cancelUrl: 'https://myaccount.ea.com/subscriptions',
    aliases: ['ea', 'ea access'],
  },
  {
    name: 'Twitch',
    domain: 'twitch.tv',
    brandColor: '#9146FF',
    category: Category.GAMING,
    cancelUrl: 'https://www.twitch.tv/subscriptions',
    aliases: ['twitch turbo', 'twitch sub'],
  },

  // ─── PRODUCTIVIDAD ────────────────────────────────────────
  {
    name: 'ChatGPT Plus',
    domain: 'openai.com',
    brandColor: '#10A37F',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://chat.openai.com/account/subscription',
    aliases: ['chatgpt', 'openai', 'gpt plus'],
  },
  {
    name: 'Claude Pro',
    domain: 'claude.ai',
    brandColor: '#D97706',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://claude.ai/settings/billing',
    aliases: ['claude', 'anthropic'],
  },
  {
    name: 'Microsoft 365',
    domain: 'microsoft.com',
    brandColor: '#0078D4',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://account.microsoft.com/services/',
    aliases: ['office 365', 'ms 365', 'office', 'microsoft office'],
  },
  {
    name: 'Notion',
    domain: 'notion.so',
    brandColor: '#000000',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://www.notion.so/my-account',
    aliases: [],
  },
  {
    name: 'Figma',
    domain: 'figma.com',
    brandColor: '#F24E1E',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://www.figma.com/settings/billing',
    aliases: [],
  },
  {
    name: 'Canva',
    domain: 'canva.com',
    brandColor: '#00C4CC',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://www.canva.com/settings/billing',
    aliases: ['canva pro'],
  },
  {
    name: 'Grammarly',
    domain: 'grammarly.com',
    brandColor: '#15C39A',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://account.grammarly.com/subscription',
    aliases: [],
  },
  {
    name: 'Linear',
    domain: 'linear.app',
    brandColor: '#5E6AD2',
    category: Category.PRODUCTIVITY,
    aliases: [],
  },
  {
    name: 'Slack',
    domain: 'slack.com',
    brandColor: '#4A154B',
    category: Category.PRODUCTIVITY,
    aliases: [],
  },
  {
    name: 'Zoom',
    domain: 'zoom.us',
    brandColor: '#2D8CFF',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://zoom.us/account/billing',
    aliases: [],
  },

  // ─── CLOUD STORAGE ─────────────────────────────────────────
  {
    name: 'iCloud+',
    domain: 'icloud.com',
    brandColor: '#3693F3',
    category: Category.CLOUD_STORAGE,
    cancelUrl: 'https://support.apple.com/en-us/HT202039',
    aliases: ['icloud', 'icloud plus'],
  },
  {
    name: 'Google One',
    domain: 'one.google.com',
    brandColor: '#4285F4',
    category: Category.CLOUD_STORAGE,
    cancelUrl: 'https://one.google.com/settings',
    aliases: ['google drive', 'google storage'],
  },
  {
    name: 'Dropbox',
    domain: 'dropbox.com',
    brandColor: '#0061FF',
    category: Category.CLOUD_STORAGE,
    cancelUrl: 'https://www.dropbox.com/account/plan',
    aliases: ['dropbox plus', 'dropbox pro'],
  },
  {
    name: 'OneDrive',
    domain: 'onedrive.com',
    brandColor: '#0078D4',
    category: Category.CLOUD_STORAGE,
    cancelUrl: 'https://account.microsoft.com/services/',
    aliases: ['one drive', 'microsoft onedrive'],
  },

  // ─── SEGURIDAD / VPN ──────────────────────────────────────
  {
    name: 'NordVPN',
    domain: 'nordvpn.com',
    brandColor: '#4687FF',
    category: Category.UTILITIES,
    cancelUrl: 'https://my.nordaccount.com/dashboard/nordvpn/',
    aliases: ['nord'],
  },
  {
    name: '1Password',
    domain: '1password.com',
    brandColor: '#0094F5',
    category: Category.UTILITIES,
    cancelUrl: 'https://my.1password.com/settings/billing',
    aliases: ['onepassword', '1pass'],
  },
  {
    name: 'ExpressVPN',
    domain: 'expressvpn.com',
    brandColor: '#DA3940',
    category: Category.UTILITIES,
    cancelUrl: 'https://www.expressvpn.com/subscriptions',
    aliases: ['express vpn'],
  },

  // ─── SALUD & FITNESS ──────────────────────────────────────
  {
    name: 'Strava',
    domain: 'strava.com',
    brandColor: '#FC4C02',
    category: Category.HEALTH_FITNESS,
    cancelUrl: 'https://www.strava.com/account',
    aliases: [],
  },
  {
    name: 'Headspace',
    domain: 'headspace.com',
    brandColor: '#F47D31',
    category: Category.HEALTH_FITNESS,
    cancelUrl: 'https://www.headspace.com/settings/subscription',
    aliases: [],
  },
  {
    name: 'Calm',
    domain: 'calm.com',
    brandColor: '#4A90D9',
    category: Category.HEALTH_FITNESS,
    cancelUrl: 'https://www.calm.com/account',
    aliases: [],
  },

  // ─── APRENDIZAJE ──────────────────────────────────────────
  {
    name: 'Duolingo',
    domain: 'duolingo.com',
    brandColor: '#58CC02',
    category: Category.NEWS_LEARNING,
    cancelUrl: 'https://www.duolingo.com/settings/account',
    aliases: ['duolingo plus', 'duolingo super'],
  },
  {
    name: 'Audible',
    domain: 'audible.com',
    brandColor: '#F8991C',
    category: Category.NEWS_LEARNING,
    cancelUrl: 'https://www.audible.com/account/overview',
    aliases: [],
  },
  {
    name: 'Kindle Unlimited',
    domain: 'amazon.com',
    brandColor: '#FF9900',
    category: Category.NEWS_LEARNING,
    cancelUrl: 'https://www.amazon.com/kindle-dbs/hz/subscribe/ku',
    aliases: ['kindle', 'ku'],
  },
  {
    name: 'Medium',
    domain: 'medium.com',
    brandColor: '#000000',
    category: Category.NEWS_LEARNING,
    cancelUrl: 'https://medium.com/me/settings/billing',
    aliases: [],
  },
  {
    name: 'Coursera',
    domain: 'coursera.org',
    brandColor: '#0056D2',
    category: Category.NEWS_LEARNING,
    cancelUrl: 'https://www.coursera.org/account-settings',
    aliases: ['coursera plus'],
  },

  // ─── NOTICIAS ─────────────────────────────────────────────
  {
    name: 'New York Times',
    domain: 'nytimes.com',
    brandColor: '#000000',
    category: Category.NEWS_LEARNING,
    cancelUrl: 'https://myaccount.nytimes.com/seg/subscription',
    aliases: ['nyt', 'ny times', 'nytimes'],
  },
  {
    name: 'The Athletic',
    domain: 'theathletic.com',
    brandColor: '#000000',
    category: Category.NEWS_LEARNING,
    cancelUrl: 'https://theathletic.com/account/',
    aliases: ['athletic'],
  },

  // ─── SOCIAL ───────────────────────────────────────────────
  {
    name: 'Tinder',
    domain: 'tinder.com',
    brandColor: '#FE3C72',
    category: Category.OTHER,
    cancelUrl: 'https://tinder.com/settings',
    aliases: ['tinder gold', 'tinder plus', 'tinder platinum'],
  },
  {
    name: 'Bumble',
    domain: 'bumble.com',
    brandColor: '#FFC629',
    category: Category.OTHER,
    cancelUrl: 'https://bumble.com/get-started',
    aliases: ['bumble premium', 'bumble boost'],
  },

  // ─── DEV TOOLS ────────────────────────────────────────────
  {
    name: 'GitHub Copilot',
    domain: 'github.com',
    brandColor: '#000000',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://github.com/settings/billing',
    aliases: ['github', 'copilot', 'gh copilot'],
  },
  {
    name: 'Cursor',
    domain: 'cursor.com',
    brandColor: '#000000',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://www.cursor.com/settings',
    aliases: ['cursor pro'],
  },
  {
    name: 'Midjourney',
    domain: 'midjourney.com',
    brandColor: '#000000',
    category: Category.PRODUCTIVITY,
    cancelUrl: 'https://www.midjourney.com/account/',
    aliases: ['mj', 'mid journey'],
  },
];
